# Generated by Django 4.2.11 on 2024-04-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wastewatch', '0002_report_date_report_resolve_explanation_report_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
